/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DiagnoseRouteImport } from './routes/diagnose'
import { Route as CalculateRouteImport } from './routes/calculate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SmellsIndexRouteImport } from './routes/smells.index'
import { Route as DiagnoseIndexRouteImport } from './routes/diagnose.index'
import { Route as SmellsSplatRouteImport } from './routes/smells.$'
import { Route as DiagnoseVacuumRouteImport } from './routes/diagnose.vacuum'
import { Route as DiagnoseSmellRouteImport } from './routes/diagnose.smell'
import { Route as DiagnoseAirflowRouteImport } from './routes/diagnose.airflow'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseRoute = DiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculateRoute = CalculateRouteImport.update({
  id: '/calculate',
  path: '/calculate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmellsIndexRoute = SmellsIndexRouteImport.update({
  id: '/smells/',
  path: '/smells/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseIndexRoute = DiagnoseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiagnoseRoute,
} as any)
const SmellsSplatRoute = SmellsSplatRouteImport.update({
  id: '/smells/$',
  path: '/smells/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseVacuumRoute = DiagnoseVacuumRouteImport.update({
  id: '/vacuum',
  path: '/vacuum',
  getParentRoute: () => DiagnoseRoute,
} as any)
const DiagnoseSmellRoute = DiagnoseSmellRouteImport.update({
  id: '/smell',
  path: '/smell',
  getParentRoute: () => DiagnoseRoute,
} as any)
const DiagnoseAirflowRoute = DiagnoseAirflowRouteImport.update({
  id: '/airflow',
  path: '/airflow',
  getParentRoute: () => DiagnoseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculate': typeof CalculateRoute
  '/diagnose': typeof DiagnoseRouteWithChildren
  '/learn': typeof LearnRoute
  '/not-found': typeof NotFoundRoute
  '/diagnose/airflow': typeof DiagnoseAirflowRoute
  '/diagnose/smell': typeof DiagnoseSmellRoute
  '/diagnose/vacuum': typeof DiagnoseVacuumRoute
  '/smells/$': typeof SmellsSplatRoute
  '/diagnose/': typeof DiagnoseIndexRoute
  '/smells/': typeof SmellsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculate': typeof CalculateRoute
  '/learn': typeof LearnRoute
  '/not-found': typeof NotFoundRoute
  '/diagnose/airflow': typeof DiagnoseAirflowRoute
  '/diagnose/smell': typeof DiagnoseSmellRoute
  '/diagnose/vacuum': typeof DiagnoseVacuumRoute
  '/smells/$': typeof SmellsSplatRoute
  '/diagnose': typeof DiagnoseIndexRoute
  '/smells': typeof SmellsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculate': typeof CalculateRoute
  '/diagnose': typeof DiagnoseRouteWithChildren
  '/learn': typeof LearnRoute
  '/not-found': typeof NotFoundRoute
  '/diagnose/airflow': typeof DiagnoseAirflowRoute
  '/diagnose/smell': typeof DiagnoseSmellRoute
  '/diagnose/vacuum': typeof DiagnoseVacuumRoute
  '/smells/$': typeof SmellsSplatRoute
  '/diagnose/': typeof DiagnoseIndexRoute
  '/smells/': typeof SmellsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculate'
    | '/diagnose'
    | '/learn'
    | '/not-found'
    | '/diagnose/airflow'
    | '/diagnose/smell'
    | '/diagnose/vacuum'
    | '/smells/$'
    | '/diagnose/'
    | '/smells/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculate'
    | '/learn'
    | '/not-found'
    | '/diagnose/airflow'
    | '/diagnose/smell'
    | '/diagnose/vacuum'
    | '/smells/$'
    | '/diagnose'
    | '/smells'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculate'
    | '/diagnose'
    | '/learn'
    | '/not-found'
    | '/diagnose/airflow'
    | '/diagnose/smell'
    | '/diagnose/vacuum'
    | '/smells/$'
    | '/diagnose/'
    | '/smells/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculateRoute: typeof CalculateRoute
  DiagnoseRoute: typeof DiagnoseRouteWithChildren
  LearnRoute: typeof LearnRoute
  NotFoundRoute: typeof NotFoundRoute
  SmellsSplatRoute: typeof SmellsSplatRoute
  SmellsIndexRoute: typeof SmellsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose': {
      id: '/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof DiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculate': {
      id: '/calculate'
      path: '/calculate'
      fullPath: '/calculate'
      preLoaderRoute: typeof CalculateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smells/': {
      id: '/smells/'
      path: '/smells'
      fullPath: '/smells/'
      preLoaderRoute: typeof SmellsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose/': {
      id: '/diagnose/'
      path: '/'
      fullPath: '/diagnose/'
      preLoaderRoute: typeof DiagnoseIndexRouteImport
      parentRoute: typeof DiagnoseRoute
    }
    '/smells/$': {
      id: '/smells/$'
      path: '/smells/$'
      fullPath: '/smells/$'
      preLoaderRoute: typeof SmellsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose/vacuum': {
      id: '/diagnose/vacuum'
      path: '/vacuum'
      fullPath: '/diagnose/vacuum'
      preLoaderRoute: typeof DiagnoseVacuumRouteImport
      parentRoute: typeof DiagnoseRoute
    }
    '/diagnose/smell': {
      id: '/diagnose/smell'
      path: '/smell'
      fullPath: '/diagnose/smell'
      preLoaderRoute: typeof DiagnoseSmellRouteImport
      parentRoute: typeof DiagnoseRoute
    }
    '/diagnose/airflow': {
      id: '/diagnose/airflow'
      path: '/airflow'
      fullPath: '/diagnose/airflow'
      preLoaderRoute: typeof DiagnoseAirflowRouteImport
      parentRoute: typeof DiagnoseRoute
    }
  }
}

interface DiagnoseRouteChildren {
  DiagnoseAirflowRoute: typeof DiagnoseAirflowRoute
  DiagnoseSmellRoute: typeof DiagnoseSmellRoute
  DiagnoseVacuumRoute: typeof DiagnoseVacuumRoute
  DiagnoseIndexRoute: typeof DiagnoseIndexRoute
}

const DiagnoseRouteChildren: DiagnoseRouteChildren = {
  DiagnoseAirflowRoute: DiagnoseAirflowRoute,
  DiagnoseSmellRoute: DiagnoseSmellRoute,
  DiagnoseVacuumRoute: DiagnoseVacuumRoute,
  DiagnoseIndexRoute: DiagnoseIndexRoute,
}

const DiagnoseRouteWithChildren = DiagnoseRoute._addFileChildren(
  DiagnoseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculateRoute: CalculateRoute,
  DiagnoseRoute: DiagnoseRouteWithChildren,
  LearnRoute: LearnRoute,
  NotFoundRoute: NotFoundRoute,
  SmellsSplatRoute: SmellsSplatRoute,
  SmellsIndexRoute: SmellsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
