/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DiagnoseRouteImport } from './routes/diagnose'
import { Route as CalculateRouteImport } from './routes/calculate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnoseIndexRouteImport } from './routes/diagnose.index'
import { Route as DiagnoseVacuumRouteImport } from './routes/diagnose.vacuum'
import { Route as DiagnoseOdorRouteImport } from './routes/diagnose.odor'
import { Route as DiagnoseAirflowRouteImport } from './routes/diagnose.airflow'

const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseRoute = DiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculateRoute = CalculateRouteImport.update({
  id: '/calculate',
  path: '/calculate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseIndexRoute = DiagnoseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiagnoseRoute,
} as any)
const DiagnoseVacuumRoute = DiagnoseVacuumRouteImport.update({
  id: '/vacuum',
  path: '/vacuum',
  getParentRoute: () => DiagnoseRoute,
} as any)
const DiagnoseOdorRoute = DiagnoseOdorRouteImport.update({
  id: '/odor',
  path: '/odor',
  getParentRoute: () => DiagnoseRoute,
} as any)
const DiagnoseAirflowRoute = DiagnoseAirflowRouteImport.update({
  id: '/airflow',
  path: '/airflow',
  getParentRoute: () => DiagnoseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculate': typeof CalculateRoute
  '/diagnose': typeof DiagnoseRouteWithChildren
  '/learn': typeof LearnRoute
  '/diagnose/airflow': typeof DiagnoseAirflowRoute
  '/diagnose/odor': typeof DiagnoseOdorRoute
  '/diagnose/vacuum': typeof DiagnoseVacuumRoute
  '/diagnose/': typeof DiagnoseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculate': typeof CalculateRoute
  '/learn': typeof LearnRoute
  '/diagnose/airflow': typeof DiagnoseAirflowRoute
  '/diagnose/odor': typeof DiagnoseOdorRoute
  '/diagnose/vacuum': typeof DiagnoseVacuumRoute
  '/diagnose': typeof DiagnoseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculate': typeof CalculateRoute
  '/diagnose': typeof DiagnoseRouteWithChildren
  '/learn': typeof LearnRoute
  '/diagnose/airflow': typeof DiagnoseAirflowRoute
  '/diagnose/odor': typeof DiagnoseOdorRoute
  '/diagnose/vacuum': typeof DiagnoseVacuumRoute
  '/diagnose/': typeof DiagnoseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculate'
    | '/diagnose'
    | '/learn'
    | '/diagnose/airflow'
    | '/diagnose/odor'
    | '/diagnose/vacuum'
    | '/diagnose/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculate'
    | '/learn'
    | '/diagnose/airflow'
    | '/diagnose/odor'
    | '/diagnose/vacuum'
    | '/diagnose'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculate'
    | '/diagnose'
    | '/learn'
    | '/diagnose/airflow'
    | '/diagnose/odor'
    | '/diagnose/vacuum'
    | '/diagnose/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculateRoute: typeof CalculateRoute
  DiagnoseRoute: typeof DiagnoseRouteWithChildren
  LearnRoute: typeof LearnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose': {
      id: '/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof DiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculate': {
      id: '/calculate'
      path: '/calculate'
      fullPath: '/calculate'
      preLoaderRoute: typeof CalculateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose/': {
      id: '/diagnose/'
      path: '/'
      fullPath: '/diagnose/'
      preLoaderRoute: typeof DiagnoseIndexRouteImport
      parentRoute: typeof DiagnoseRoute
    }
    '/diagnose/vacuum': {
      id: '/diagnose/vacuum'
      path: '/vacuum'
      fullPath: '/diagnose/vacuum'
      preLoaderRoute: typeof DiagnoseVacuumRouteImport
      parentRoute: typeof DiagnoseRoute
    }
    '/diagnose/odor': {
      id: '/diagnose/odor'
      path: '/odor'
      fullPath: '/diagnose/odor'
      preLoaderRoute: typeof DiagnoseOdorRouteImport
      parentRoute: typeof DiagnoseRoute
    }
    '/diagnose/airflow': {
      id: '/diagnose/airflow'
      path: '/airflow'
      fullPath: '/diagnose/airflow'
      preLoaderRoute: typeof DiagnoseAirflowRouteImport
      parentRoute: typeof DiagnoseRoute
    }
  }
}

interface DiagnoseRouteChildren {
  DiagnoseAirflowRoute: typeof DiagnoseAirflowRoute
  DiagnoseOdorRoute: typeof DiagnoseOdorRoute
  DiagnoseVacuumRoute: typeof DiagnoseVacuumRoute
  DiagnoseIndexRoute: typeof DiagnoseIndexRoute
}

const DiagnoseRouteChildren: DiagnoseRouteChildren = {
  DiagnoseAirflowRoute: DiagnoseAirflowRoute,
  DiagnoseOdorRoute: DiagnoseOdorRoute,
  DiagnoseVacuumRoute: DiagnoseVacuumRoute,
  DiagnoseIndexRoute: DiagnoseIndexRoute,
}

const DiagnoseRouteWithChildren = DiagnoseRoute._addFileChildren(
  DiagnoseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculateRoute: CalculateRoute,
  DiagnoseRoute: DiagnoseRouteWithChildren,
  LearnRoute: LearnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
